export default function getUnidades() {
	return [
		"USA - BARB - TRANSFERENCIA",
		"USA - BARBACENA",
		"USA - CONGONHAS",
		"USA - CONS. LAFAIETE",
		"USA - MUNICIPIOS",
		"USA - SAO J. DEL REI",
		"USB - ALTO RIO DOCE",
		"USB - BARBACENA",
		"USB - BARROSO",
		"USB - BOM SUCESSO",
		"USB - CARANDAI",
		"USB - CONGONHAS",
		"USB - CONS. LAFAIETE",
		"USB - ENTRE RIOS",
		"USB - IBERTIOGA",
		"USB - LAGOA DOURADA",
		"USB - MADRE DE DEUS",
		"USB - NAZARENO",
		"USB - OURO BRANCO",
		"USB - PIRANGA",
		"USB - RESENDE COSTA",
		"USB - RIO ESPERA",
		"USB - SAO J. DEL REI",
		"USB - SAO TIAGO",
		"USB - TIRADENTES",
	];
}
