import getIcon from "./Icons";
import { IMenu } from "@/Types/Menu";

const MenuInit: IMenu[] = [
	{
		Icon: null,
		iconIfy: getIcon("Dashboard"),
		primary: "Inicio",
		url: "/",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "dashboard:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Almoxarifado"),
		primary: "Req. Almoxarifado",
		url: "/requerimentos/almoxarifado",
		attentionColor: "#f59e0b",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "requerimentos:open:almoxarifado",
	},
	{
		Icon: null,
		iconIfy: getIcon("Farmacia"),
		primary: "Req. Farmácia",
		url: "/requerimentos/farmacia",
		attentionColor: "#0ea5e9",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "requerimentos:open:farmacia",
	},
	{
		Icon: null,
		iconIfy: getIcon("Requerimentos"),
		primary: "Req. CME",
		url: "/requerimentos/cme",
		attentionColor: "#22c55e",
		isOpen: false,
		subMenu: [],
		divider: true,
		permission: "requerimentos:open:cme",
	},
	{
		Icon: null,
		iconIfy: getIcon("Requerimentos"),
		primary: "Gestão Almox.",
		url: "/requerimentos/gestao/almoxarifado",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "requerimentos:almoxarifado:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Requerimentos"),
		primary: "Gestão Farmácia",
		url: "/requerimentos/gestao/farmacia",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "requerimentos:farmacia:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Requerimentos"),
		primary: "Gestão CME",
		url: "/requerimentos/gestao/cme",
		isOpen: false,
		subMenu: [],
		divider: true,
		permission: "requerimentos:cme:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Usuarios"),
		primary: "Usuários",
		url: "/usuarios",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "usuarios:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Bases"),
		primary: "Bases",
		url: "/bases",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "bases:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Setores"),
		primary: "Setores",
		url: "/setores",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "setores:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Cargos"),
		primary: "Cargos",
		url: "/cargos",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "cargos:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Ambulancias"),
		primary: "Ambulâncias",
		url: "/ambulancias",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "ambulancias:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Almoxarifado"),
		primary: "Almoxarifado",
		url: "#",
		isOpen: false,
		permission: "produtos:menu",
		divider: false,
		subMenu: [
			{
				Icon: null,
				iconIfy: getIcon("CategoriasProduto"),
				primary: "Categorias de Produto",
				url: "/categorias-produto",
				isOpen: false,
				permission: "categorias-produto:menu",
				subMenu: [],
				divider: false,
			},
			{
				Icon: null,
				iconIfy: getIcon("Produtos"),
				primary: "Produtos",
				url: "/produtos",
				isOpen: false,
				permission: "produtos:menu",
				subMenu: [],
				divider: false,
			},
		],
	},
	{
		Icon: null,
		iconIfy: getIcon("Farmacia"),
		primary: "Farmácia",
		url: "#",
		isOpen: false,
		permission: "medicamentos:menu",
		divider: false,
		subMenu: [
			{
				Icon: null,
				iconIfy: getIcon("CategoriasMedicamento"),
				primary: "Categorias de Medicamento",
				url: "/categorias-medicamento",
				isOpen: false,
				permission: "categorias-medicamento:menu",
				subMenu: [],
				divider: false,
			},
			{
				Icon: null,
				iconIfy: getIcon("Medicamentos"),
				primary: "Medicamentos",
				url: "/medicamentos",
				isOpen: false,
				permission: "medicamentos:menu",
				subMenu: [],
				divider: false,
			},
		],
	},
	{
		Icon: null,
		iconIfy: getIcon("Medicos"),
		primary: "Médicos",
		url: "/medicos",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "medicos:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Receituarios"),
		primary: "Receituários",
		url: "/receituarios",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "receituarios:menu",
	},
	{
		Icon: null,
		iconIfy: getIcon("Bases"),
		primary: "Visitas às Bases",
		url: "/visitas-bases",
		isOpen: false,
		subMenu: [],
		divider: false,
		permission: "visitas-bases:menu",
	},
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Requerimentos"),
	// 	primary: "Requerimentos de FAPH",
	// 	url: "/requerimentos",
	// 	isOpen: false,
	// 	permission: "requerimentos:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Manifestacoes"),
	// 	primary: "Manifestações",
	// 	url: "/manifestacoes",
	// 	isOpen: false,
	// 	permission: "manifestacoes:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Disparos"),
	// 	primary: "Disparos",
	// 	url: "/disparos",
	// 	isOpen: false,
	// 	permission: "disparos:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Assuntos"),
	// 	primary: "Manifestações Assuntos",
	// 	url: "/assuntos/manifestacoes",
	// 	isOpen: false,
	// 	permission: "assuntos:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Acoes"),
	// 	primary: "Manifestações Ações",
	// 	url: "/acoes/manifestacoes",
	// 	isOpen: false,
	// 	permission: "acoes:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Cargos"),
	// 	primary: "Cargos",
	// 	url: "/cargos",
	// 	isOpen: false,
	// 	permission: "cargos:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Setores"),
	// 	primary: "Setores",
	// 	url: "/setores",
	// 	isOpen: false,
	// 	permission: "setores:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Tags"),
	// 	primary: "Tags Conversas",
	// 	url: "/tags_conversas",
	// 	isOpen: false,
	// 	permission: "tagsConversas:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Usuarios"),
	// 	primary: "Usuários",
	// 	url: "/usuarios",
	// 	isOpen: false,
	// 	permission: "usuarios:menu",
	// 	subMenu: [],
	// 	divider: false,
	// },
	// {
	// 	Icon: null,
	// 	iconIfy: getIcon("Relatorios"),
	// 	primary: "Relatorios",
	// 	url: "#",
	// 	isOpen: false,
	// 	permission: "relatorios:menu",
	// 	subMenu: [
	// 		{
	// 			Icon: null,
	// 			iconIfy: getIcon("RelatorioManifestacoes"),
	// 			primary: "Consolidado Manifestações",
	// 			url: "/relatorios/consolidado/manifestacoes",
	// 			isOpen: false,
	// 			permission: "relatorios:consolidado:manifestacoes",
	// 			subMenu: [],
	// 			divider: false,
	// 		},
	// 		{
	// 			Icon: null,
	// 			iconIfy: getIcon("RelatorioNotasUnidades"),
	// 			primary: "Notas Unidades",
	// 			url: "/relatorios/notas_unidades",
	// 			isOpen: false,
	// 			permission: "relatorios:nota_unidades",
	// 			subMenu: [],
	// 			divider: false,
	// 		},
	// 		{
	// 			Icon: null,
	// 			iconIfy: getIcon("RelatorioTempoResposta"),
	// 			primary: "Tempo de Resposta",
	// 			url: "/relatorios/tempo_resposta",
	// 			isOpen: false,
	// 			permission: "relatorios:tempo_resposta",
	// 			subMenu: [],
	// 			divider: false,
	// 		},
	// 		{
	// 			Icon: null,
	// 			iconIfy: getIcon("RelatorioTempoRespostaDetalhado"),
	// 			primary: "Tempo de Resposta Detalhado",
	// 			url: "/relatorios/tempo_resposta_detalhado",
	// 			isOpen: false,
	// 			permission: "relatorios:tempo_resposta_detalhado",
	// 			subMenu: [],
	// 			divider: false,
	// 		},
	// 	],
	// 	divider: false,
	// },
];

export default MenuInit;
