import {
	CATEGORIAS_PRODUTO_PERMISSIONS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	PRODUTOS_PERMISSIONS,
	REQUERIMENTOS_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
	ESTOQUES_PERMISSIONS,
	GESTAO_MENU_PERMISSIONS,
	USUARIOS_PERMISSIONS,
	AllPermissionGroup,
	BASES_PERMISSIONS,
	SETORES_PERMISSIONS,
	CARGOS_PERMISSIONS,
	AMBULANCIAS_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

const ALX_DASHBOARD_PERMISSIONS = definePermissionGroup([
	// Dashboard Requerimentos
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.COUNT_ALMOXARIFADO,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.TABLE_ALMOXARIFADO,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.CARD_VISITAS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.CARD_VENCIMENTOS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.CARD_MOVIMENTACOES,
] as const);

const ALX_REQUERIMENTOS_PERMISSIONS = definePermissionGroup([
	REQUERIMENTOS_PERMISSIONS.NEW,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE_ANY,
	REQUERIMENTOS_PERMISSIONS.SEND_ALMOXARIFADO,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.OPEN_SETORES,
	REQUERIMENTOS_PERMISSIONS.OPEN_BASES,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
] as const);

const ALX_ESTOQUES_PERMISSIONS = definePermissionGroup([
	ESTOQUES_PERMISSIONS.BASES,
	ESTOQUES_PERMISSIONS.MENU,
	ESTOQUES_PERMISSIONS.TABLE,
	ESTOQUES_PERMISSIONS.NEW,
	ESTOQUES_PERMISSIONS.HISTORICO,
	ESTOQUES_PERMISSIONS.BASES,
	ESTOQUES_PERMISSIONS.ADD_PRODUTO,
] as const);

// ------------------------------- Setor do almoxarifado -----------------

export const Almoxarifado = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	GESTAO_MENU_PERMISSIONS.MENU,
	...AllPermissionGroup(USUARIOS_PERMISSIONS),
	...AllPermissionGroup(AMBULANCIAS_PERMISSIONS),
	...AllPermissionGroup(CARGOS_PERMISSIONS),
	...AllPermissionGroup(SETORES_PERMISSIONS),
	...AllPermissionGroup(BASES_PERMISSIONS),
	...AllPermissionGroup(PRODUTOS_PERMISSIONS),
	...AllPermissionGroup(CATEGORIAS_PRODUTO_PERMISSIONS),
	...ALX_DASHBOARD_PERMISSIONS,
	...ALX_REQUERIMENTOS_PERMISSIONS,
	...ALX_ESTOQUES_PERMISSIONS,
] as const);

export const AuxAlmoxarifado = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	...AllPermissionGroup(PRODUTOS_PERMISSIONS),
	...ALX_DASHBOARD_PERMISSIONS,
	...ALX_ESTOQUES_PERMISSIONS,
] as const);

export const Separador = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	...ALX_DASHBOARD_PERMISSIONS,
	ESTOQUES_PERMISSIONS.MENU,
	ESTOQUES_PERMISSIONS.TABLE,
	ESTOQUES_PERMISSIONS.HISTORICO,
] as const);

export const AlmoxarifadoPermissionsByCargo = {
	[TypeCargo.Almoxarifado]: Almoxarifado,
	[TypeCargo.AuxAlmoxarifado]: AuxAlmoxarifado,
	[TypeCargo.Separador]: Separador,
} as const;
