import {
	CATEGORIAS_PRODUTO_PERMISSIONS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	PRODUTOS_PERMISSIONS,
	REQUERIMENTOS_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

const ALL_DASHBOARD_PERMISSIONS = definePermissionGroup([
	// Dashboard Requerimentos
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.COUNT_ALMOXARIFADO,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.TABLE_ALMOXARIFADO,
] as const);

const ALL_REQUERIMENTOS_PERMISSIONS = definePermissionGroup([
	REQUERIMENTOS_PERMISSIONS.NEW,
	REQUERIMENTOS_PERMISSIONS.VIEW,
	REQUERIMENTOS_PERMISSIONS.EDIT,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE,
	REQUERIMENTOS_PERMISSIONS.SEND_ALMOXARIFADO,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.OPEN_SETORES,
	REQUERIMENTOS_PERMISSIONS.OPEN_BASES,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
] as const);

const ALL_CATEGORIAS_PRODUTO_PERMISSIONS = definePermissionGroup([
	CATEGORIAS_PRODUTO_PERMISSIONS.VIEW,
	CATEGORIAS_PRODUTO_PERMISSIONS.MENU,
	CATEGORIAS_PRODUTO_PERMISSIONS.TABLE,
	CATEGORIAS_PRODUTO_PERMISSIONS.NEW,
	CATEGORIAS_PRODUTO_PERMISSIONS.EDIT,
	CATEGORIAS_PRODUTO_PERMISSIONS.DELETE,
] as const);

const ALL_PRODUTOS_PERMISSIONS = definePermissionGroup([
	PRODUTOS_PERMISSIONS.VIEW,
	PRODUTOS_PERMISSIONS.MENU,
	PRODUTOS_PERMISSIONS.TABLE,
	PRODUTOS_PERMISSIONS.NEW,
	PRODUTOS_PERMISSIONS.EDIT,
	PRODUTOS_PERMISSIONS.DELETE,
] as const);

// ------------------------------- Setor do almoxarifado --

export const Almoxarifado = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
	...ALL_DASHBOARD_PERMISSIONS,
	...ALL_PRODUTOS_PERMISSIONS,
	...ALL_CATEGORIAS_PRODUTO_PERMISSIONS,
	...ALL_REQUERIMENTOS_PERMISSIONS,
] as const);

export const AuxAlmoxarifado = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
	...ALL_DASHBOARD_PERMISSIONS,
	...ALL_PRODUTOS_PERMISSIONS,
] as const);

export const Separador = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	...ALL_DASHBOARD_PERMISSIONS,
] as const);

export const AlmoxarifadoPermissionsByCargo = {
	[TypeCargo.Almoxarifado]: Almoxarifado,
	[TypeCargo.AuxAlmoxarifado]: AuxAlmoxarifado,
	[TypeCargo.Separador]: Separador,
} as const;
