import {
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	REQUERIMENTOS_PERMISSIONS,
	REQUERIMENTOS_OPEN_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

export const Base = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.NEW,
	REQUERIMENTOS_PERMISSIONS.VIEW,
	REQUERIMENTOS_PERMISSIONS.EDIT,
	REQUERIMENTOS_PERMISSIONS.DELETE,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	REQUERIMENTOS_PERMISSIONS.FARMACIA_MENU,
	REQUERIMENTOS_PERMISSIONS.CME_MENU,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.SEND_ALMOXARIFADO,
	REQUERIMENTOS_PERMISSIONS.SEND_FARMACIA,
	REQUERIMENTOS_PERMISSIONS.SEND_CME,
	REQUERIMENTOS_OPEN_PERMISSIONS.ALMOXARIFADO,
	REQUERIMENTOS_OPEN_PERMISSIONS.CME,
	REQUERIMENTOS_OPEN_PERMISSIONS.FARMACIA,
	...Object.values(DASHBOARD_REQUERIMENTOS_PERMISSIONS),
] as const);

export const BasePermissionsByCargo = {
	[TypeCargo.Facilitador]: Base,
} as const;
