import {
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	REQUERIMENTOS_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

export const CME = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	REQUERIMENTOS_PERMISSIONS.NEW,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE_ANY,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.CME_MENU,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
	// Dashboard Requerimentos
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.COUNT_CME,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.TABLE_CME,
] as const);

export const CMEPermissionsByCargo = {
	[TypeCargo.CME]: CME,
} as const;
