import {
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	REQUERIMENTOS_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

export const Enfermagem = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.NEW,
	VISITAS_BASES_PERMISSIONS.EDIT,
	VISITAS_BASES_PERMISSIONS.DELETE,
	VISITAS_BASES_PERMISSIONS.MENU,
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE_ANY,
	REQUERIMENTOS_PERMISSIONS.ALMOXARIFADO_MENU,
	REQUERIMENTOS_PERMISSIONS.FARMACIA_MENU,
	REQUERIMENTOS_PERMISSIONS.CME_MENU,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	...Object.values(DASHBOARD_REQUERIMENTOS_PERMISSIONS),
] as const);

export const EnfermagemPermissionsByCargo = {
	[TypeCargo.Enfermagem]: Enfermagem,
} as const;
