import {
	CATEGORIAS_MEDICAMENTO_PERMISSIONS,
	DEFAULT_PERMISSIONS_CATALOG,
	definePermissionGroup,
	MEDICAMENTOS_PERMISSIONS,
	MEDICOS_PERMISSIONS,
	RECEITUARIOS_PERMISSIONS,
	REQUERIMENTOS_PERMISSIONS,
	VISITAS_BASES_PERMISSIONS,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS,
} from "./PermissionGroups";
import { TypeCargo } from "./Types";

export const Farmacia = definePermissionGroup([
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.PERFIL_VIEW,
	DEFAULT_PERMISSIONS_CATALOG.DASHBOARD_MENU,
	// Dashboard Requerimentos
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.COUNT_FARMACIA,
	DASHBOARD_REQUERIMENTOS_PERMISSIONS.TABLE_FARMACIA,
	// Categoria Medicamentos
	CATEGORIAS_MEDICAMENTO_PERMISSIONS.MENU,
	CATEGORIAS_MEDICAMENTO_PERMISSIONS.TABLE,
	CATEGORIAS_MEDICAMENTO_PERMISSIONS.NEW,
	CATEGORIAS_MEDICAMENTO_PERMISSIONS.EDIT,
	CATEGORIAS_MEDICAMENTO_PERMISSIONS.DELETE,
	// Medicamentos
	MEDICAMENTOS_PERMISSIONS.MENU,
	MEDICAMENTOS_PERMISSIONS.TABLE,
	MEDICAMENTOS_PERMISSIONS.VIEW,
	MEDICAMENTOS_PERMISSIONS.NEW,
	MEDICAMENTOS_PERMISSIONS.EDIT,
	MEDICAMENTOS_PERMISSIONS.DELETE,
	MEDICAMENTOS_PERMISSIONS.TOGGLE_ACTIVE,
	// Médicos
	MEDICOS_PERMISSIONS.MENU,
	MEDICOS_PERMISSIONS.TABLE,
	MEDICOS_PERMISSIONS.VIEW,
	MEDICOS_PERMISSIONS.NEW,
	MEDICOS_PERMISSIONS.EDIT,
	MEDICOS_PERMISSIONS.TOGGLE_ACTIVE,
	// Receituários
	RECEITUARIOS_PERMISSIONS.VIEW,
	RECEITUARIOS_PERMISSIONS.NEW,
	RECEITUARIOS_PERMISSIONS.EDIT,
	RECEITUARIOS_PERMISSIONS.MENU,
	// Requerimentos
	REQUERIMENTOS_PERMISSIONS.VIEW_ANY,
	REQUERIMENTOS_PERMISSIONS.EDIT_ANY,
	REQUERIMENTOS_PERMISSIONS.DELETE_ANY,
	REQUERIMENTOS_PERMISSIONS.STATUS,
	REQUERIMENTOS_PERMISSIONS.ITENS,
	REQUERIMENTOS_PERMISSIONS.FARMACIA_MENU,
	REQUERIMENTOS_PERMISSIONS.TABLE,
	REQUERIMENTOS_PERMISSIONS.PDF,
	REQUERIMENTOS_PERMISSIONS.STATUS_ANALISE,
	REQUERIMENTOS_PERMISSIONS.STATUS_SEPARACAO,
	REQUERIMENTOS_PERMISSIONS.STATUS_FINALIZADO,
	REQUERIMENTOS_PERMISSIONS.STATUS_CANCELADO,
	// Visitas Bases
	VISITAS_BASES_PERMISSIONS.VIEW,
	VISITAS_BASES_PERMISSIONS.MENU,
] as const);

export const FarmaciaPermissionsByCargo = {
	[TypeCargo.Farmaceutica]: Farmacia,
	[TypeCargo.TecFarmacia]: Farmacia,
} as const;
